### ISSUE TITLE
Link for "Help"

### ISSUE THREAD

**Issue by Novezeil** [thingles/foreground#194]
Just noticed a tiny problem.

"Help" under gear icon is pointing to ~/wiki/Help:Contents regardless whether it's under root path.

**Comment by Hutchy68** [comment]
Had a few minutes this morning to look at this issue. It is something we really need to correct. @paladox is correct, we do set the hard link with the piece of code. The issue is older and line 139 as pointed out is now line 138 from code changes to bring the reference up-to-date.

To correct it we:

1. Need to stop using a hard path
2. Flexibility for user to set a path if they want 'Help' under tools
3. Don't break existing sites using true or false to show Help under tools

I didn't really want to introduce another setting, but after testing, looking at `$wgArticlePath` and other methods it occurred to me, what if the user doesn't even want to host wiki help pages, has a wiki farm, or hosts them somewhere else?

`pathToHelpPage => '/wiki/Help:Contents'` would be the default. If someone has the `showHelpUnderTools` set to true, it won't break their wiki. If someone has it set to false, it won't break their wiki. If the user wants to use MediaWiki.org's help pages, another external link, a different Help:Page, or `$wgArticlePath` to Help:Contents they can. Some examples:

```
pathToHelpPage = 'https://www.mediawiki.org/wiki/Help:Contents'  // external
pathToHelpPage = 'http://mydomainname.org/Help'  // external
pathToHelpPage = 'wiki/Help:Home'  // Help namespace alternate page name
pathToHelpPage = '/Help:Contents'  // root install
pathToHelpPage = '/ourwiki/Help:Contents'  // alternate $wgArticlePath of /ourwiki/$1
```

Thoughts? I'll push a PR for testing, I already have it coded and working on my development wiki.

**Comment by Hutchy68** [comment]
@Novezeil I know it has been a long time since you opened this issue, sorry for the delay in addressing it. 

Personally, I would rather use Option#2. It brings us back into the default use of MW message units to set things Globally and not dependent on the skin.

**Comment by Hutchy68** [comment]
fixed, see #272 set help page with `MediaWiki:Helppage`

**Comment by paladox** [comment]
Seems it is duplicated under navigation and tools.

**Comment by Hutchy68** [comment]
Always was, need to update docs. If it's in the MW:Sidebar it will show twice.

**Comment by paladox** [comment]
Oh ok.
