### ISSUE TITLE
VisualEditor's "edit" and "edit source" icons don't have icons

### ISSUE THREAD

**Issue by patrakov** [thingles/foreground#285]
I have installed VisualEditor. But, even though compatibility with it is mentioned in the theme changelog, it is not 100% complete. Namely, the "Edit" and "Edit source" menu items now don't have icons.

**Comment by patrakov** [comment]
![noicons](https://cloud.githubusercontent.com/assets/2943163/16085970/bbafbf3e-333f-11e6-8f1a-b10999b8c9fe.png)

**Comment by patrakov** [comment]
Two issues here.

1. There is no javascript handler that prepends a pencil icon to "li#ca-ve-edit a"
2. The existing handler that prepends a pencil icon to "li#ca-edit a" does not seem to work because VisualEditor later replaces the whole content of the "a" tag [in this line](https://github.com/wikimedia/mediawiki-extensions-VisualEditor/blob/b33cd5d8f1d5f2b91acddba67066127a2c5c7c39/modules/ve-mw/init/targets/ve.init.mw.DesktopArticleTarget.init.js#L455) thus losing the icon.

**Comment by Hutchy68** [comment]
This is easy to fix, but it might break depending on load timing. Try it and clear the cache, or hard page reload.

You will have to add some js to MediaWiki:Foreground.js page. Create it if it doesn't exist. Use the `(window).load` to try and make sure it loads last. Drop the `a` from `li#ca-edit` and tweak the `div` class to `drop-icon-ve` prepends above the `<a>` tag so when it is rewritten the icon isn't deleted by VE.

```
$(window).load(function() {
    if ($("li#ca-ve-edit").length) {
    $('li#ca-ve-edit a').prepend('<div class="drop-icon"><i class="fa fa-pencil-square-o fa-fw"></i></div>')
    $('li#ca-edit').prepend('<div class="drop-icon-ve"><i class="fa fa-code fa-fw"></i></div>')	
    }
});
```

First, the js checks to see if `li#ca-ve-edit` exists because VE is in use. If it does, it will prepend the icons moving the pencil to to the `ca-ve-edit a` and code brackets </> to `ca-edit`.

Here is the CSS to account for the new placement of the icon before the `<a>` tag. Place that into MediaWiki:Foreground.css page.

```
.drop-icon-ve {
    float: left;
    margin: 0 4px 0 9px;
}
```

![image](https://cloud.githubusercontent.com/assets/3527469/21077800/36e85e24-bf25-11e6-8a4a-12c40294db3f.png)

**Comment by Hutchy68** [comment]
So I have solved this issue by:

1. Dividing up the JavaScript
2. All icons load with doc ready in JS --> except edit icons
3. Edit source (the standard edit) and ve-edit are loaded window.load

What happens is all icons are placed, then when the window is ready JS adds the icons for edit and ve-edit if needed. You don't see the missing icons (dropdown so they don't show) and it really is milliseconds.

**Comment by Hutchy68** [comment]
Closing, but didn't make the change. The icons are loading fine with doc.ready. Not sure why and I am scratching my head.

Reopen if this becomes an issue again.

**Comment by Hutchy68** [comment]
I revisited this issue as I started seeing the icons failing to append today which was the behavior I expected. It still is rather fragile, I wish Visual Editor would just add to the page actions instead of inserting after the fact.
